### ISSUE TITLE
Peer Review issue (Cannot open app on expo)

### ISSUE THREAD

**Issue by cadlamp** [DavyHyun/ReSplit#21]
I followed your steps to open the app on my expo go app. It did not complete bundling because it popped up a screen that said "Unable to resolve module ../config/environments from C:\Users\cllam\Resplit\screens\scanner.js". It continued to explain that the file from "import Environment from '../config/environments'" did not exist. I tried it a couple more times, but the problem still persisted. For reference, I followed the steps, I cloned the repo, I did "npm install" then I did "npx expo start". I already had node.js and npm, as well as, the expo go app.

**Comment by cadlamp** [comment]
I realized after reading the developer documentation that I need a config folder. I would add this information to the user manual or somehow make it more intuitive.

**Comment by Whu-UW** [comment]
Added to documentation to explain this step so there isn't confusion
