### ISSUE TITLE
Limited use only

### ISSUE THREAD

**Issue by chienvle** [DavyHyun/ReSplit#22]
When I either upload a picture or take one and proceed to the last page, clicking the "Calculate New Receipt!" button redirects me to the home page. However, an issue arises during this process. The "take picture" function fails to process and advance to the subsequent page where the group size is queried. Similarly, with repeated use, the camera roll option exhibits the same behavior.

Device: iPhone 15 Pro
OS: iOS 17.1.1
ReSplit Version: v1.0.0-beta

**Comment by Whu-UW** [comment]
No longer running into this issue
